### ISSUE TITLE
Upgrade to dotLess 1.4.1

### ISSUE THREAD

**Issue by Huppie** [scott-xu/System.Web.Optimization.Less#23]
Hi,

I ran into an issue trying to use System.Web.Optimization.Less in combination with a newer bootstrap version. It looks like this package is still using an old version of dotLess. Could you have a look if the package can be upgraded to use dotLess 1.4.1?

Thanks!

**Comment by sanmolhec** [comment]
+1.

Please upgrade to dotLess 1.5.x

Thanks

**Comment by sanmolhec** [comment]
Hi.

As a solution while System.Web.Optimization.Less integrates dotLess 1.5.X natively, a trick can be made for you to use:

-     install System.Web.Optimization.Less.
-     update the dotLess nuget package (to its current version 1.5.2.0).
-     force on the web.config the bridge from the old library to the new one:

`<runtime> 
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
        ... 
         
        <dependentAssembly> <assemblyIdentity name="dotless.Core" publicKeyToken="96b446c9e63eae34" culture="neutral"/> 
            <bindingRedirect oldVersion="1.4.0.0" newVersion="1.5.2.0"/> 
        </dependentAssembly> 
    </assemblyBinding> 
</runtime>`

With these steps we are using the new dotLess library and can already import *.less files into *.less files.

I hope it helps them.

For more information see this website: http://www.brendanforster.com/blog/yet-another-implement-less-in-aspnetmvc-post.html

Greetings, Hector.

**Comment by twenzel** [comment]
Created PR #28

**Comment by scott-xu** [comment]
fixed in the latest release.
