### ISSUE TITLE
Nuget package version different from assembly version

### ISSUE THREAD

**Issue by Alex-Tsyganok** [scott-xu/System.Web.Optimization.Less#26]
Hello,

Starting from 1.3.2 version all NuGet packages contains System.Web.Optimization.Less.dll assembly with same version (1.3.0)

Currently there is no way to distinguish assemblies from different packages.
It would be nice if assembly version matches NuGet package version.

**Comment by scott-xu** [comment]
fixed in the latest release, by using the SDK styled csproj
