### ISSUE TITLE
Please support dotless versions > 1.40

### ISSUE THREAD

**Issue by matttrakker** [scott-xu/System.Web.Optimization.Less#27]
Hello,

your dependency information is telling that your package supports ">= 1.4.0".
But when I upgrade this package to something >= 1.4.0 (1.4.4 or the latest 1.5.2) your System.Web.Optimization.Less is raising an exception because it cannot solve dotless 1.4.0.

It would be great if you update your dependency description or even better, if you allow to use >= 1.4.0

Thanks and best regards,

matthias

**Comment by sanmolhec** [comment]
+1

**Comment by sanmolhec** [comment]
Hi. 

As a solution while System.Web.Optimization.Less integrates dotLess 1.5.X natively, a trick can be made for you to use:

- install System.Web.Optimization.Less.
- update the dotLess nuget package (to its current version 1.5.2.0).
- force on the web.config the bridge from the old library to the new one:

<runtime>
	  ...
	  
	  <dependentAssembly>
		<assemblyIdentity name="dotless.Core" publicKeyToken="96b446c9e63eae34" culture="neutral"/>
		<bindingRedirect oldVersion="1.4.0.0" newVersion="1.5.2.0"/>
	  </dependentAssembly>
	</assemblyBinding>
</runtime>


With these steps we are using the new dotLess library and can already import *.less files into *.less files.

I hope it helps them.

For more information see this website:  [http://www.brendanforster.com/blog/yet-another-implement-less-in-aspnetmvc-post.html](http://www.brendanforster.com/blog/yet-another-implement-less-in-aspnetmvc-post.html)

Greetings, Hector.

**Comment by twenzel** [comment]
Created PR #28 .

**Comment by scott-xu** [comment]
fixed in the latest release
