### ISSUE TITLE
Incompatability with dotless version 1.6.7

### ISSUE THREAD

**Issue by iannewson** [scott-xu/System.Web.Optimization.Less#31]
Using this package with the latest version of dotless results in the following error:

Could not load type 'dotless.Core.configuration.WebConfigConfigurationLoader' from assembly 'dotless.Core, Version=1.6.7.0, Culture=neutral, PublicKeyToken=96b446c9e63eae34'.

**Comment by petrosmm** [comment]
see https://github.com/dotless/dotless/issues/548

**Comment by CZEMacLeod** [comment]
Any progress on this?
I am tripping over this issue now and would prefer not to have to work with forks and my own builds. :/

**Comment by petrosmm** [comment]
I e-mailed him the other day, he's located in china. He didn't answer lol.

**Comment by petrosmm** [comment]
a new version has been released! thank you @scott-xu !!!

**Comment by scott-xu** [comment]
@petrosmm u r welcome
